version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /resources/
  static_dir: resources/
- url: /.*
  script: Expenses.app
# Needed for remote console.
- url: /remote_api/*
  script: google.appengine.ext.remote_api.handler.application
  
builtins:
- remote_api: on
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]