# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=32)),
                ('bank', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=3)),
                ('factor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('object', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recordedOn', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ExpApp.BankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='PayementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('surName', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='beneficiaries',
            field=models.ManyToManyField(to='ExpApp.Person'),
        ),
        migrations.AddField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(to='ExpApp.Category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ExpApp.Currency'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ExpApp.PayementType'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recordedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recorder', to='ExpApp.Person'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='owner',
            field=models.ManyToManyField(to='ExpApp.Person'),
        ),
    ]
