# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpApp', '0002_auto_20161217_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
